### ISSUE TITLE
Typescript's new moduleResolution breaks errlop's typing

### ISSUE THREAD

**Issue by kwasimensah** [bevry/errlop#196]
See https://github.com/microsoft/TypeScript/issues/49160 . Typescript's new moduleResolution type doesn't look at the top-level types field in your package.json (it now uses the logic specified in https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing)

**Comment by balupton** [comment]
Same deal as https://github.com/bevry/istextorbinary/issues/270

**Comment by balupton** [comment]
Boundation successfully updated this package and didn't encounter this error. Is it still a problem for you?

**Comment by balupton** [comment]
this should be resolved with v7.3.0
https://github.com/bevry/errlop/commit/3071fb2184772e950d1c3322ed1c1931502b3951#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
