### ISSUE TITLE
Version 1.7.0 trigger build error with Webpack 2.1.5 / node 5.4.1 / npm 3.3.12

### ISSUE THREAD

**Issue by xLitil** [bevry/errlop#41]
Hello,

The new version 1.7.0 is pulled by editions@2.2.0 -> yeoman-generator@2.0.5 -> yeoman-environment@2.6.0  -> webpack  : https://github.com/webpack/webpack-cli/blob/v2.1.5/package.json

This version is not compatible with node 5.4.1 / npm 3.3.12 : 
```
19:26:45 [ERROR] npm ERR! code EMISSINGARG
19:26:45 [ERROR] 
19:26:45 [ERROR] npm ERR! typeerror Error: Missing required argument #1
```

Is it possible to publish a fix ?
And publish a major release for changes appeared in 1.7.0 in order to avoid the "^" semver hell :)

Regards,

**Comment by zackshen** [comment]
i met this bug today too.
i install `i18next-scanner' then the same error happened @xLitil @BevryMe

**Comment by balupton** [comment]
working on a fix now

**Comment by balupton** [comment]
what sortobject version is being used, as sortobject v2 only supports node >= 8

**Comment by balupton** [comment]
anyway, new versions of `editions` and `errlop` have been published, so if you clear your install cache, to make sure editions is v2.3.0 and errlop is v2.0.0 then you should be ok

**Comment by zackshen** [comment]
thanks @balupton , i'm sorry, i use node==6.3.0 to install errlop, it was broken

**Comment by zackshen** [comment]
sortobject version is 1.1.1, it requires 'editions@^1.1.1'

**Comment by balupton** [comment]
okay, let me publish a version that support node >= 4

**Comment by zackshen** [comment]
i'm maintaining a product which built on old version node(6.3.0)，refactor the build system would token more effort。

**Comment by balupton** [comment]
okay, v2.4.0 of sortobject is being published with node >= 5 support, with the latest versions of editions and errlop

**Comment by zackshen** [comment]
@balupton thanks

**Comment by balupton** [comment]
As it has been nearly 4 months now since Node v10 has become the minimum supported and maintained version, can I drop support for Node v5, v6, v8
