### ISSUE TITLE
install errlop failed under node==6.5.0

### ISSUE THREAD

**Issue by zackshen** [bevry/errlop#42]
Hi @BevryMe 
Today i installed errlop@2.0.0 sortobject@2.4.0 under node(6.5.0) again, the error still exists

## Error
```
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
```

**Comment by balupton** [comment]
Are you sure it is these packages? I'm not sure why that error would be showing for those packages. It also works for all our ci infrastructure and my own machine, as I was never able to reproduce that problem.

**Comment by balupton** [comment]
Seems your issue is an issue with that npm version. Try upgrading your npm

https://github.com/npm/npm/issues/9659

**Comment by balupton** [comment]
Please follow up with npm support as the issue seems to be in npm
