### ISSUE TITLE
Types missing from package

### ISSUE THREAD

**Issue by Silic0nS0ldier** [bevry/errlop#44]
Dependabot update failure (https://github.com/userfrosting/gulp-uf-bundle-assets/pull/66) just tipped me off to an issue with `errlop`, it appears a package update performed by automation removed the reference to the generated types.

Build failure error indicating missing types reference: https://github.com/userfrosting/gulp-uf-bundle-assets/runs/695432218#step:7:4
Breaking commit: https://github.com/bevry/errlop/commit/f64f0d101561fb460b518df7e94bbedad45238cf

Looking at the changelog automation (https://github.com/bevry/boundation/blob/master/HISTORY.md) it seems probable this is a result of a recent change.

**Comment by balupton** [comment]
@Silic0nS0ldier should be fixed now
