### ISSUE TITLE
https://master.errlop.bevry.surge.sh/ produces a certificate error

### ISSUE THREAD

**Issue by moltar** [bevry/errlop#67]
Visiting https://master.errlop.bevry.surge.sh/docs/globals.html

Produces a cert error.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/491247/90371909-d6685000-e099-11ea-9db0-a30eb10487d2.png">

**Comment by balupton** [comment]
Yeah, please do it with http instead of https. Where as the https link?

**Comment by moltar** [comment]
> Yeah, please do it with http instead of https. Where was the https link?

In the README

**Comment by balupton** [comment]
> In the README

Sorry, where in README?

https://github.com/bevry/errlop/blame/master/README.md#L38

**Comment by balupton** [comment]
Do you have an auto-https extension installed?

**Comment by moltar** [comment]
> Do you have an auto-https extension installed?

Ha, that is correct! That was a super good guess :)

https://atlas.eff.org/domains/surge.sh.html

With that ext disabled, everything works fine.

Sorry for the false issue!
